### ISSUE TITLE
Add link to RTD documentation on homepage

### ISSUE THREAD

**Issue by 0x326** [PyFilesystem/pyfilesystem.org#1]
It's hard to find the Sphinx documentation for this project from the homepage.  Is there a way you can put a link on the homepage that says "Documentation" and points to https://pyfilesystem2.readthedocs.io/en/latest/ ?

**Comment by willmcgugan** [comment]
You can find the api reference by clicking on the Help link. But I guess I could make it more prominent.

**Comment by willmcgugan** [comment]
Better?

**Comment by 0x326** [comment]
@willmcgugan Perfect.  Thanks!
